services:
  address-service:
    build:
      context: address-service
    environment:
      - DATABASE_URL=mysql://root:root@address-db:3306/address
    ports:
      - 3000:80
    depends_on:
      address-db:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy &&
            npm run start"

  address-db:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=address
    volumes:
      - address-db:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 3

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    volumes:
      - ./address-service/openapi:/openapi
    environment:
      SWAGGER_JSON: /openapi/swagger.json

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  address-db:
    