services:
  address-service:
    build:
      context: ./address-service
    ports:
      - 3000:3000
  # address-db:
  #   image: mariadb:11
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=root
  #     - MARIADB_DATABASE=address
  #   ports:
  #     - 3306:3306
    