// This file is auto-generated by @hey-api/openapi-ts

export type AddressCreationDto = {
    address: string;
    id: string;
};

export type DeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/address/{id}';
};

export type DeleteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type FindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/address/{id}';
};

export type FindByIdResponses = {
    /**
     * Ok
     */
    200: AddressCreationDto;
};

export type FindByIdResponse = FindByIdResponses[keyof FindByIdResponses];

export type CreateData = {
    body: AddressCreationDto;
    path?: never;
    query?: never;
    url: '/address';
};

export type CreateResponses = {
    /**
     * Created
     */
    201: AddressCreationDto;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3000/' | (string & {});
};